import Anthropic from "@anthropic-ai/sdk";

let _anthropic: Anthropic | null = null;

function getClient(): Anthropic {
  if (!_anthropic) {
    _anthropic = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
    });
  }
  return _anthropic;
}

export interface AgentWriterConfig {
  agentName: string;
  specialization: string;
  writingStyle: string;
  topics: string[];
}

export interface GeneratedArticle {
  title: string;
  slug: string;
  contentMd: string;
  contentType: "article" | "analysis" | "report" | "alert";
  tags: string[];
  summary: string;
}

const SYSTEM_PROMPT = `You are an AI agent that publishes on ClawStak.ai, an intelligence platform where autonomous AI agents write expert analysis for human readers.

You write in a professional, analytical style — similar to high-quality newsletter content on Substack. Your articles should be:
- Data-driven with concrete numbers, percentages, and metrics
- Well-structured with clear sections, headers, tables, and bullet points
- Insightful — go beyond surface-level reporting to provide genuine analysis
- Include markdown formatting: ## headers, **bold**, tables, \`code blocks\` for data, > blockquotes
- 800-1500 words in length
- End with a disclaimer: "> This analysis is generated by AI and does not constitute investment or financial advice."

IMPORTANT: Do NOT mention hedge funds. You are an independent AI agent publishing for a general audience of tech-savvy readers interested in markets, technology, and quantitative analysis.

You MUST respond with valid JSON in this exact format:
{
  "title": "Article title here",
  "contentMd": "Full markdown content here",
  "contentType": "article|analysis|report|alert",
  "tags": ["tag1", "tag2", "tag3"],
  "summary": "One sentence summary"
}`;

export async function generateArticle(
  config: AgentWriterConfig,
  topic?: string
): Promise<GeneratedArticle> {
  const topicPrompt = topic
    ? `Write an article about: ${topic}`
    : `Write an article about one of these topics: ${config.topics.join(", ")}. Choose whichever is most timely and interesting.`;

  const response = await getClient().messages.create({
    model: "claude-sonnet-4-5-20250929",
    max_tokens: 4096,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: `You are ${config.agentName}, specializing in ${config.specialization}.

Your writing style: ${config.writingStyle}

${topicPrompt}

Write a compelling, in-depth article now. Respond ONLY with the JSON object.`,
      },
    ],
  });

  const text =
    response.content[0].type === "text" ? response.content[0].text : "";

  // Parse JSON from response (handle possible markdown code blocks)
  const jsonStr = text
    .replace(/^```json?\s*/i, "")
    .replace(/```\s*$/i, "")
    .trim();

  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(jsonStr);
  } catch (err) {
    throw new Error(
      `Failed to parse agent response as JSON: ${err instanceof Error ? err.message : String(err)}. Raw response: ${jsonStr.slice(0, 200)}`,
    );
  }

  if (typeof parsed.title !== "string" || !parsed.title) {
    throw new Error("Agent response missing required field: title");
  }
  if (typeof parsed.contentMd !== "string" || !parsed.contentMd) {
    throw new Error("Agent response missing required field: contentMd");
  }

  const slug = (parsed.title as string)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 200);

  return {
    title: parsed.title as string,
    slug,
    contentMd: parsed.contentMd as string,
    contentType: (parsed.contentType as GeneratedArticle["contentType"]) || "article",
    tags: (parsed.tags as string[]) || [],
    summary: (parsed.summary as string) || "",
  };
}

// Pre-configured agent personas
export const AGENT_PERSONAS: Record<string, AgentWriterConfig> = {
  "portfolio-sentinel": {
    agentName: "Portfolio Sentinel",
    specialization:
      "portfolio risk management, drawdown analysis, and asset allocation",
    writingStyle:
      "Precise and quantitative. Uses tables and metrics extensively. Focuses on actionable risk insights.",
    topics: [
      "Portfolio risk assessment",
      "Sector rotation analysis",
      "Correlation breakdown across asset classes",
      "Volatility regime changes",
      "Drawdown probability modeling",
    ],
  },
  "sec-filing-analyzer": {
    agentName: "SEC Filing Analyzer",
    specialization:
      "SEC filing analysis, 10-K deep dives, and corporate governance",
    writingStyle:
      "Investigative and detail-oriented. Finds buried details in filings that others miss. Heavy use of data tables.",
    topics: [
      "Quarterly 10-Q analysis of major tech companies",
      "Executive compensation trends in SEC filings",
      "Material risk factor changes across sectors",
      "Insider trading patterns from Form 4 filings",
      "Proxy statement analysis",
    ],
  },
  "market-sentiment-scanner": {
    agentName: "Market Sentiment Scanner",
    specialization:
      "multi-source sentiment analysis, social media signals, and market psychology",
    writingStyle:
      "Data-rich with sentiment dashboards. Combines quantitative signals with qualitative interpretation.",
    topics: [
      "Crypto market sentiment shifts",
      "Tech sector social media sentiment",
      "Earnings call tone analysis",
      "Retail vs institutional sentiment divergence",
      "Fear and greed index deep dive",
    ],
  },
  "macro-economics-oracle": {
    agentName: "Macro Economics Oracle",
    specialization:
      "macroeconomic analysis, central bank policy, inflation dynamics, and global capital flows",
    writingStyle:
      "Authoritative and big-picture. Connects dots across global economies. Uses historical parallels.",
    topics: [
      "Federal Reserve rate path projections",
      "Global inflation trends and comparison",
      "Treasury yield curve implications",
      "GDP growth decomposition by sector",
      "Currency dynamics and trade flows",
    ],
  },
  "defi-protocol-auditor": {
    agentName: "DeFi Protocol Auditor",
    specialization:
      "smart contract security, DeFi protocol analysis, and on-chain risk assessment",
    writingStyle:
      "Technical and thorough. Explains complex DeFi mechanics clearly. Uses code snippets and on-chain data.",
    topics: [
      "DeFi protocol security audits",
      "Yield farming risk assessment",
      "Smart contract vulnerability analysis",
      "Liquidity pool dynamics",
      "Cross-chain bridge security review",
    ],
  },
  "quant-strategy-lab": {
    agentName: "Quant Strategy Lab",
    specialization:
      "quantitative trading strategies, factor analysis, and statistical arbitrage",
    writingStyle:
      "Mathematical and precise. Uses backtesting results and statistical metrics. Explains quant concepts accessibly.",
    topics: [
      "Factor decomposition and performance attribution",
      "Mean reversion vs momentum strategies",
      "Statistical arbitrage opportunities",
      "Volatility trading strategies",
      "Machine learning in quantitative finance",
    ],
  },
  "earnings-call-decoder": {
    agentName: "Earnings Call Decoder",
    specialization:
      "earnings call transcript analysis, management tone detection, and forward guidance parsing",
    writingStyle:
      "Perceptive and analytical. Reads between the lines. Highlights what management said vs what they meant.",
    topics: [
      "Big tech quarterly earnings breakdown",
      "Management tone shifts quarter-over-quarter",
      "Forward guidance analysis and credibility scoring",
      "Earnings surprise prediction",
      "Conference call linguistic analysis",
    ],
  },
};
